# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/da/Desktops/Desktop1/prektika3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/da/Desktops/Desktop1/prektika3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/da/Desktops/Desktop1/prektika3/CMakeFiles /home/da/Desktops/Desktop1/prektika3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/da/Desktops/Desktop1/prektika3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 4

# Build rule for target.
4 : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 4
.PHONY : 4

# fast build rule for target.
4/fast:
	$(MAKE) -f CMakeFiles/4.dir/build.make CMakeFiles/4.dir/build
.PHONY : 4/fast

#=============================================================================
# Target rules for targets named 3

# Build rule for target.
3 : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 3
.PHONY : 3

# fast build rule for target.
3/fast:
	$(MAKE) -f CMakeFiles/3.dir/build.make CMakeFiles/3.dir/build
.PHONY : 3/fast

#=============================================================================
# Target rules for targets named 1

# Build rule for target.
1 : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 1
.PHONY : 1

# fast build rule for target.
1/fast:
	$(MAKE) -f CMakeFiles/1.dir/build.make CMakeFiles/1.dir/build
.PHONY : 1/fast

#=============================================================================
# Target rules for targets named 2

# Build rule for target.
2 : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 2
.PHONY : 2

# fast build rule for target.
2/fast:
	$(MAKE) -f CMakeFiles/2.dir/build.make CMakeFiles/2.dir/build
.PHONY : 2/fast

prak1.o: prak1.c.o

.PHONY : prak1.o

# target to build an object file
prak1.c.o:
	$(MAKE) -f CMakeFiles/1.dir/build.make CMakeFiles/1.dir/prak1.c.o
.PHONY : prak1.c.o

prak1.i: prak1.c.i

.PHONY : prak1.i

# target to preprocess a source file
prak1.c.i:
	$(MAKE) -f CMakeFiles/1.dir/build.make CMakeFiles/1.dir/prak1.c.i
.PHONY : prak1.c.i

prak1.s: prak1.c.s

.PHONY : prak1.s

# target to generate assembly for a file
prak1.c.s:
	$(MAKE) -f CMakeFiles/1.dir/build.make CMakeFiles/1.dir/prak1.c.s
.PHONY : prak1.c.s

prak2.o: prak2.c.o

.PHONY : prak2.o

# target to build an object file
prak2.c.o:
	$(MAKE) -f CMakeFiles/2.dir/build.make CMakeFiles/2.dir/prak2.c.o
.PHONY : prak2.c.o

prak2.i: prak2.c.i

.PHONY : prak2.i

# target to preprocess a source file
prak2.c.i:
	$(MAKE) -f CMakeFiles/2.dir/build.make CMakeFiles/2.dir/prak2.c.i
.PHONY : prak2.c.i

prak2.s: prak2.c.s

.PHONY : prak2.s

# target to generate assembly for a file
prak2.c.s:
	$(MAKE) -f CMakeFiles/2.dir/build.make CMakeFiles/2.dir/prak2.c.s
.PHONY : prak2.c.s

prak3.o: prak3.c.o

.PHONY : prak3.o

# target to build an object file
prak3.c.o:
	$(MAKE) -f CMakeFiles/3.dir/build.make CMakeFiles/3.dir/prak3.c.o
.PHONY : prak3.c.o

prak3.i: prak3.c.i

.PHONY : prak3.i

# target to preprocess a source file
prak3.c.i:
	$(MAKE) -f CMakeFiles/3.dir/build.make CMakeFiles/3.dir/prak3.c.i
.PHONY : prak3.c.i

prak3.s: prak3.c.s

.PHONY : prak3.s

# target to generate assembly for a file
prak3.c.s:
	$(MAKE) -f CMakeFiles/3.dir/build.make CMakeFiles/3.dir/prak3.c.s
.PHONY : prak3.c.s

prak4.o: prak4.c.o

.PHONY : prak4.o

# target to build an object file
prak4.c.o:
	$(MAKE) -f CMakeFiles/4.dir/build.make CMakeFiles/4.dir/prak4.c.o
.PHONY : prak4.c.o

prak4.i: prak4.c.i

.PHONY : prak4.i

# target to preprocess a source file
prak4.c.i:
	$(MAKE) -f CMakeFiles/4.dir/build.make CMakeFiles/4.dir/prak4.c.i
.PHONY : prak4.c.i

prak4.s: prak4.c.s

.PHONY : prak4.s

# target to generate assembly for a file
prak4.c.s:
	$(MAKE) -f CMakeFiles/4.dir/build.make CMakeFiles/4.dir/prak4.c.s
.PHONY : prak4.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... 4"
	@echo "... 3"
	@echo "... edit_cache"
	@echo "... 1"
	@echo "... rebuild_cache"
	@echo "... 2"
	@echo "... prak1.o"
	@echo "... prak1.i"
	@echo "... prak1.s"
	@echo "... prak2.o"
	@echo "... prak2.i"
	@echo "... prak2.s"
	@echo "... prak3.o"
	@echo "... prak3.i"
	@echo "... prak3.s"
	@echo "... prak4.o"
	@echo "... prak4.i"
	@echo "... prak4.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

